title: "DynamisG"
description: "Something about me"
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


url: "https://dynamisg210.github.io"
baseurl: ""

# 博客链接
permalink: /blog/:year/:month/:day/:title/

# 时区
timezone: Asia/Taipei

future: true

collections:
  projects:
    output: true
    permalink: /projects/:name/

logo: /assets/img/logo2.png

